<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>DisperSim3D</RootNamespace>
    <AssemblyName>DisperSim3D</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Title>DisperSim3D</Title>
    <Description>Open Source 3D Gas Dispersion Analysis Software</Description>
    <Company>Daniel Wagner Oliveira de Medeiros</Company>
    <Product>DisperSim3D</Product>
    <Copyright>Copyright © 2026 Daniel Wagner Oliveira de Medeiros</Copyright>
    <Version>1.0.0</Version>
    <NoWarn>WFO1000</NoWarn>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
    <PackageReference Include="DockPanelSuite" Version="3.1.1" />
    <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\Models3D\CSTR.obj" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Icons\*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Icons\Air.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
