<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>DisperSim3D.CLI</RootNamespace>
    <AssemblyName>DisperSim3D.CLI</AssemblyName>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DisperSim3D\DisperSim3D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\bin\FluidX3D.dll" Condition="Exists('..\bin\FluidX3D.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </None>
  </ItemGroup>

</Project>
